### ISSUE TITLE
Блок схема проекта

### ISSUE THREAD

**Issue by Grigorii777** [liqwidon/project-x#1]

**Comment by liqwidon** [comment]
http://www.plantuml.com/plantuml/png/HOxH3SCW34J_RmeMo0PLbLKSS2jNALJ4BXzLTuy5Glb2xxXxydeeLRNtZhAzE6em2JyqoQaqRAPQibDwikAFsKcL6jT9aVRecuVbgEBrgtVGbskOH1y1NByizxw11nTqYzEKZwSd9kFtvZ2SM3adF_e4
![HOxH3SCW34J_RmeMo0PLbLKSS2jNALJ4BXzLTuy5Glb2xxXxydeeLRNtZhAzE6em2JyqoQaqRAPQibDwikAFsKcL6jT9aVRecuVbgEBrgtVGbskOH1y1NByizxw11nTqYzEKZwSd9kFtvZ2SM3adF_e4](https://user-images.githubusercontent.com/58599778/115375793-cd0a2700-a1d6-11eb-864a-1f27ff967515.png)

code:


@startuml
object ui {
window
button
widget
}

object drawer
object calc {
function
}

object saver 
object api

ui --> calc
api --> calc
calc --> drawer
drawer --> ui
calc <--> saver
@enduml
