### ISSUE TITLE
Сделать простенький интерфейс с помощью PyQt

### ISSUE THREAD

**Issue by Proctocheck** [liqwidon/project-x#6]
что-то получше чем вот это
![image](https://user-images.githubusercontent.com/56172709/115768621-3a72af00-a3b3-11eb-9e72-38b3c3a985ce.png)

**Comment by Proctocheck** [comment]
появились успехи
![image](https://user-images.githubusercontent.com/56172709/115778128-d81fab80-a3be-11eb-9404-3364998d0483.png)

**Comment by liqwidon** [comment]
nice cack bra

**Comment by Proctocheck** [comment]
![Uploading image.png…]()

**Comment by Proctocheck** [comment]
![image](https://user-images.githubusercontent.com/56172709/115895712-65b4d700-a463-11eb-8a71-3e0112b79465.png)

**Comment by liqwidon** [comment]
жесть чел как ты это сделал
